name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run ktlint
      # You may pin to the exact commit or the version.
      # uses: lucasnlm/ktlint-action@6d01bcc1303a3bb6ce1c47b5bec1cd352f039989
      uses: lucasnlm/ktlint-action@v1.0.1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
